<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_-</name>
   <tag></tag>
   <elementGuidId>06bba26c-6b38-4855-b35e-f63d64b2d4bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.product-quantity > button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-product']/section/div/div/div[2]/div[10]/div[3]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9ffe74b-d2b3-4671-b600-63b5a358f40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>minus</value>
      <webElementGuid>d536d7d4-5bc3-437a-8eb6-3617dd6f7f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>3c89ff91-9450-44a2-99dd-dee964335d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-product&quot;)/section[@class=&quot;page-product-info&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;page-product-info-wrap&quot;]/div[@class=&quot;page-product-info-right&quot;]/div[@class=&quot;page-product-select&quot;]/div[@class=&quot;page-product-info-quantity&quot;]/div[@class=&quot;product-quantity&quot;]/button[1]</value>
      <webElementGuid>f47ff0cc-10bb-462a-b0cd-fa2a728f25eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-product']/section/div/div/div[2]/div[10]/div[3]/div/button</value>
      <webElementGuid>759ec1a3-f51d-4650-8afe-240611b7834d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số lượng'])[1]/following::button[1]</value>
      <webElementGuid>86a19937-855c-4914-ab40-2eba5b9e64ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vui lòng chọn biến thể'])[1]/following::button[1]</value>
      <webElementGuid>a4b3fd71-31ca-4b76-abc8-3969317a1cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::button[1]</value>
      <webElementGuid>b256300f-c250-43bf-8146-05599a2493db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WD14 WITH ZEST'])[3]/preceding::button[2]</value>
      <webElementGuid>d371c35f-eb02-4a51-a837-87fad06f4d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-']/parent::*</value>
      <webElementGuid>f0d144be-4557-4289-9244-1252623be81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[3]/div/button</value>
      <webElementGuid>4a3dc67c-9100-48f7-8066-19f8237d0f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '-' or . = '-')]</value>
      <webElementGuid>403bf15b-2995-418f-ae14-2be5aa104d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
