<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>91c9708a-f14c-42de-9c67-8bfaeb714e62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.f-header-top-icon-cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[name()='svg'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>350ee212-3478-4b09-ae82-44223a7e5457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>2e4799fd-34c2-4ad1-bb18-1adb2b9a2474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>82141746-c9e8-47e5-97c8-6ce9fcd5797d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 17 23</value>
      <webElementGuid>a5cceb52-f4e3-4391-be5a-c1907c1b0b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>502a90be-c0c1-486b-83fa-316592fb463a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>03c8142d-5758-4cb2-a626-85b7c202e70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f-header&quot;)/section[@class=&quot;f-header-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;f-header-top-wrap&quot;]/div[@class=&quot;f-header-top-tools&quot;]/div[@class=&quot;f-header-top-icons&quot;]/a[@class=&quot;f-header-top-icon-cart&quot;]/svg[1]</value>
      <webElementGuid>579a88c7-228b-4b1e-9ecd-95f5843a7327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotline: 1900 636 510'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>5e3b5544-e15d-486b-a450-5ca99abbfb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKINCARE'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>73779383-bac4-4f26-9166-3b9fa2e10d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DANH MỤC SẢN PHẨM'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>39db8a8a-185b-4161-a090-ba6913908670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang điểm'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>e0076726-4690-4e19-8f86-9bdc29f7756f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
