<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Anh_editcustomername</name>
   <tag></tag>
   <elementGuidId>1d7262c6-95c6-40a5-a94d-4461c2a7c889</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editcustomer-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#editcustomer-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>192fc4dc-00b1-4ee7-bb80-9c6bb5ce8756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>editcustomer[name]</value>
      <webElementGuid>29cce0bf-8396-4e29-ac0a-93698c68391e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editcustomer-name</value>
      <webElementGuid>e74a2e70-ca1c-41c3-8653-f772ab6d1b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>317848e9-4c74-43cd-8780-1eda8fdcce73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-data form-control form__field form__field--text</value>
      <webElementGuid>65470658-3c79-4a66-ac39-c525e32ed053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editcustomer-name&quot;)</value>
      <webElementGuid>4dc7e469-fabc-4a78-92b5-3fedb10d3378</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editcustomer-name']</value>
      <webElementGuid>ba868616-37e9-4b65-b565-cb17b29536eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-edit']/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>3b45288e-a41d-4078-9488-53cce2a2cb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>b23faf53-dbf1-454a-a8bc-903b97fd732a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'editcustomer[name]' and @id = 'editcustomer-name' and @type = 'text']</value>
      <webElementGuid>66c677ea-4b1b-4d4e-8e8b-787c475f481b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
