<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nhp s in thoi_editcustomeremail</name>
   <tag></tag>
   <elementGuidId>0d330d0a-ab00-44dd-beb8-39b60133f831</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editcustomer-email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#editcustomer-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>794f3163-ea55-4916-93d7-5ed828a573c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>editcustomer[email]</value>
      <webElementGuid>1ead762e-a82a-4573-a83a-238f57379d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editcustomer-email</value>
      <webElementGuid>4b7f4454-a0cc-4bc0-aba6-7bb694caae12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>df75d288-9cca-4f75-9a95-e8a0a20b19b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-data form-control form__field form__field--text</value>
      <webElementGuid>ba3cd6f3-1ba5-4ea8-9035-8fb8db0dbe0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editcustomer-email&quot;)</value>
      <webElementGuid>5ee01620-a406-4b6c-af5a-8cf419293b9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editcustomer-email']</value>
      <webElementGuid>dcc33726-444d-48cd-9f10-325139d16c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-edit']/div/div[2]/div[2]/div[3]/div/input</value>
      <webElementGuid>c3123fd4-6245-4c05-8e3b-78eb2d9203fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>c7cbcb7f-f205-417d-90c4-b72d7d905b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'editcustomer[email]' and @id = 'editcustomer-email' and @type = 'email']</value>
      <webElementGuid>bf05a1c7-d76a-4d29-b713-76c5f5e71031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
