<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_a ch giao hng_editcustomeraddress</name>
   <tag></tag>
   <elementGuidId>23abdb3a-05d4-4cc8-a2a9-a31590363d30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editcustomer-address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#editcustomer-address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4db2409f-b015-4fc4-9177-116995537813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>editcustomer[address]</value>
      <webElementGuid>bfd14fd0-7bc5-4ffa-8169-41cb963fdf2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editcustomer-address</value>
      <webElementGuid>d1fb675c-d7fa-4113-9c0d-6baa4ec59f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1b535ca-95f3-4095-be8c-5c11a0044fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-data form-control form__field form__field--text</value>
      <webElementGuid>51aa97fe-4512-4808-8e44-36c1a6a83add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editcustomer-address&quot;)</value>
      <webElementGuid>fe9bbfda-f160-43d8-ade6-dfadc0bb38df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editcustomer-address']</value>
      <webElementGuid>0451a207-a78f-4709-9937-61c6520cc53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cod-method-form']/div[4]/div/input</value>
      <webElementGuid>5a8f9214-efa0-484f-825a-3634e4149eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>64df9863-45f0-4210-a217-21b21c618a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'editcustomer[address]' and @id = 'editcustomer-address' and @type = 'text']</value>
      <webElementGuid>f158ce5c-5428-41e6-b8c7-753ffa818a6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
