<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nhp h tn_editcustomerphone</name>
   <tag></tag>
   <elementGuidId>b1fdfb9b-5455-4009-a68f-f5f48e2eb2c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editcustomer-phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#editcustomer-phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e171d6a-3722-49aa-995f-105c9b148f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>editcustomer[phone]</value>
      <webElementGuid>3e1963f5-7c56-4581-9e6e-cf07f7889635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editcustomer-phone</value>
      <webElementGuid>7efb464e-7fe8-4918-845a-167442110716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>318a3dba-d88f-42b0-92c3-489a7b024ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-data form-control form__field form__field--text</value>
      <webElementGuid>9eb107d4-c0cc-4600-9d21-ec2b48f804cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>55941363-c117-4b1d-b172-23d663dc4ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>5d88b9d2-16e5-407a-a2ea-7400cf2b6145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editcustomer-phone&quot;)</value>
      <webElementGuid>03ef986b-3c30-4ef0-be3c-0b586a821455</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editcustomer-phone']</value>
      <webElementGuid>23bf2c56-b148-4a20-acb9-69abee85b244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-edit']/div/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>38225f93-c6f8-43b9-adc3-ce560133f1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>063917b4-7483-403c-81e7-448815aaf9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'editcustomer[phone]' and @id = 'editcustomer-phone' and @type = 'text']</value>
      <webElementGuid>1dd77f35-f4de-49cd-8e6c-1c444398abbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
