<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mua Online</name>
   <tag></tag>
   <elementGuidId>11270063-b409-47ea-80e9-1ec3e6c6dfb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buynow']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buynow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f54480e9-fc9c-4f91-af9d-e01ac1174a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buynow</value>
      <webElementGuid>d152d699-8bdc-4cf7-b69f-05d6ffb64088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mua Online</value>
      <webElementGuid>ee55566e-9432-4310-b20e-6dc8ae71255b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buynow&quot;)</value>
      <webElementGuid>34736691-95cd-4cce-b81d-514f101abb3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buynow']</value>
      <webElementGuid>548aa920-56dc-46ad-8449-aae22eef8b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-product']/section/div/div/div[2]/div[13]/div[2]/button</value>
      <webElementGuid>dfda8d2e-d174-4815-832a-2525487e5112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhắc nhở tôi'])[1]/following::button[1]</value>
      <webElementGuid>83423d09-5392-4cb5-89e9-1d329a1b16af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::button[2]</value>
      <webElementGuid>7c03c8d6-9b10-400e-b6cb-db20fbd686e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm vào giỏ'])[1]/preceding::button[1]</value>
      <webElementGuid>7ad32d4b-ab56-46de-8268-37c30dd3f644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mua Online']/parent::*</value>
      <webElementGuid>773e6083-6931-4f73-85eb-53325eade670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/button</value>
      <webElementGuid>7ce09233-e9a3-4085-bae5-fcdcaf0d3980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buynow' and (text() = 'Mua Online' or . = 'Mua Online')]</value>
      <webElementGuid>9480853c-853e-4609-bea5-ef671c2c5a17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
