<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Xo</name>
   <tag></tag>
   <elementGuidId>d2e6e561-c6a3-40cc-98cd-bc0cb048c3af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='cartformpage']/div/div/div/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dafad8e2-2bd0-4bad-84ee-02abc84ef9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart/change?line=1&amp;quantity=0</value>
      <webElementGuid>eb74a511-4b97-4668-9fc0-6379167f530a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart</value>
      <webElementGuid>6ed80115-bc7c-403c-92b6-fdd87d7b83af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xoá</value>
      <webElementGuid>1070723f-ca94-4c33-bad2-5f81dfe1d9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartformpage&quot;)/div[@class=&quot;table-cart&quot;]/div[@class=&quot;cart-group single&quot;]/div[@class=&quot;item line-item line-item-container&quot;]/div[@class=&quot;left&quot;]/div[@class=&quot;item-remove&quot;]/div[@class=&quot;remove&quot;]/a[@class=&quot;cart&quot;]</value>
      <webElementGuid>0fb230b9-94c3-4d22-8695-87811a4c6a29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cartformpage']/div/div/div/div/div[2]/div/a</value>
      <webElementGuid>84445e96-0355-45c8-94c0-799d64d2698c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Xoá')]</value>
      <webElementGuid>04e6a931-5308-4570-a700-e01fa2126487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoàn tất'])[1]/following::a[2]</value>
      <webElementGuid>4c759ff0-d28d-4a23-bdb0-bcceb69ae4f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin đặt hàng'])[1]/following::a[2]</value>
      <webElementGuid>a24bc63b-519c-4d33-9bcd-8a7f2770acc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Màu 1-17] Son Tint Nước Romand Siêu Lì, Lâu Trôi Glasting Water Tint 4g'])[1]/preceding::a[1]</value>
      <webElementGuid>62b6989a-d145-4071-b617-c89d669c9631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thành tiền:'])[1]/preceding::a[2]</value>
      <webElementGuid>1d5f01c4-12f2-4870-b289-202911c21f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Xoá']/parent::*</value>
      <webElementGuid>6780f0ab-2efb-48a0-a1cb-d08ab79fe1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cart/change?line=1&amp;quantity=0')]</value>
      <webElementGuid>19d08aea-ef71-437c-a8ca-b9b2c37a777f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/a</value>
      <webElementGuid>c1ad8c8e-3dac-40da-9c7d-ec2cfef7164f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cart/change?line=1&amp;quantity=0' and (text() = 'Xoá' or . = 'Xoá')]</value>
      <webElementGuid>a3990f10-ba6e-400b-9850-4b5f9983f324</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
