<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mu 1-17 Son Tint Nc Romand Siu L, Lu _6e6177</name>
   <tag></tag>
   <elementGuidId>707a925a-a28b-4bea-b898-4296ddc2207d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#updates_1050344280</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[contains(text(),'[New][NEW DEW] Son Tint Bóng Merzy Dạng Thạch, Bền')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2053d27d-bc72-4823-9df8-61c64348a92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vid</name>
      <type>Main</type>
      <value>1050344280</value>
      <webElementGuid>0e54982a-4bfb-4685-8eb3-849dbe93cf10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quantity</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0121412d-8e2b-4635-abcf-89f3f7c4cfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-invent</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>1e5aade9-4f75-4fb5-a5f0-dcb1c57365e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product</name>
      <type>Main</type>
      <value>1022205303</value>
      <webElementGuid>e9682969-0c7c-48d0-a027-cedd19b4ed3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a311a082-d266-44e5-a0e6-c8ae155eb794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>fb7f06c3-b551-4ca9-adf5-a205511c958c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>updates[]</value>
      <webElementGuid>1f80fb63-5d83-49cb-933a-8020b5d13ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c4ac92c4-a2db-4773-b76b-23ef1dc8e3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>updates_1050344280</value>
      <webElementGuid>8c53bd5f-4e37-402c-9260-8b11bac710b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>17900000</value>
      <webElementGuid>fb2f1c1a-6d22-4e41-bdf8-41002131d0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ad63ce1d-8de9-4e35-93b2-203a0b756d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tc line-item-qty item-quantity</value>
      <webElementGuid>3b757b7b-72e2-4a0f-8a33-d2a10ca22c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;updates_1050344280&quot;)</value>
      <webElementGuid>c8e7ed7a-0ca8-4328-a938-f6fd99eda7d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='updates_1050344280']</value>
      <webElementGuid>42f072d7-f042-4a62-bae9-153942f787f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cartformpage']/div/div/div/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>e074c2e6-71b4-4ba0-a20e-94a6fdc4ed4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>4d410fd7-15b5-4383-97a3-8a46d3526386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'updates[]' and @id = 'updates_1050344280']</value>
      <webElementGuid>da61d387-f397-4735-85a4-c5d8d72c6267</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
