<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_516.000</name>
   <tag></tag>
   <elementGuidId>8a71a11e-4aaa-42f5-a387-9012d9825dc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.totalprice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart-buy-order-box']/section[3]/div[3]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>feadfe69-2f74-4a22-8a94-33aaeac559af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>totalprice</value>
      <webElementGuid>4aed1fca-6f7d-468e-afd6-8f5e621b7279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>516.000₫</value>
      <webElementGuid>a50e38bd-5b83-4b4f-8fbe-04d6a004f29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-buy-order-box&quot;)/section[@class=&quot;section-info-total&quot;]/div[@class=&quot;summary-total&quot;]/span[@class=&quot;totalprice&quot;]</value>
      <webElementGuid>78a43412-2996-4238-b499-b51ed3613fdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-buy-order-box']/section[3]/div[3]/span[2]</value>
      <webElementGuid>3a0423ca-26f7-4fd5-b224-9ba92d8fd490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền:'])[1]/following::span[1]</value>
      <webElementGuid>c6f7eaf4-0fe1-4fa3-b2d0-f51f01b7a807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Miễn phí'])[1]/following::span[2]</value>
      <webElementGuid>5f2d7041-9270-4b63-bf37-f2bf5d6ba98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ĐẶT HÀNG NGAY'])[1]/preceding::span[1]</value>
      <webElementGuid>a52666e5-8920-4bbe-9023-ea810d8cc242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin khách mua hàng'])[1]/preceding::span[1]</value>
      <webElementGuid>f4d1035c-2a61-452a-9296-12be3350391e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span[2]</value>
      <webElementGuid>4939b1b6-8c14-4d93-8d3c-118af344198b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '516.000₫' or . = '516.000₫')]</value>
      <webElementGuid>ec16c3f2-8e8e-4b1e-9089-b63db91f9111</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
