<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_358.000</name>
   <tag></tag>
   <elementGuidId>d16a50e0-005a-44cd-bbaf-71e80ad9e321</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.totalprice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart-buy-order-box']/section[3]/div[3]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bde44039-bafa-4b4b-9ddc-4b27f4820a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>totalprice</value>
      <webElementGuid>2284bcfc-a3c8-404d-84d3-e7e0177ceed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>358.000₫</value>
      <webElementGuid>186c68e3-55cb-45dc-8548-f347821789c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-buy-order-box&quot;)/section[@class=&quot;section-info-total&quot;]/div[@class=&quot;summary-total&quot;]/span[@class=&quot;totalprice&quot;]</value>
      <webElementGuid>55706820-c036-47f9-ae27-d1112c1a0aab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-buy-order-box']/section[3]/div[3]/span[2]</value>
      <webElementGuid>6f5bdc2b-c7cc-40f4-a342-b3d9bd9253ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền:'])[1]/following::span[1]</value>
      <webElementGuid>068e157c-4793-49d6-9515-2b28593e378e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Miễn phí'])[1]/following::span[2]</value>
      <webElementGuid>df164ed2-a8c5-4895-bff9-d0acfbcabd17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ĐẶT HÀNG NGAY'])[1]/preceding::span[1]</value>
      <webElementGuid>d4ae7984-2dd9-4988-9c74-70d85f850c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin khách mua hàng'])[1]/preceding::span[1]</value>
      <webElementGuid>640e66ff-d9e2-4c0b-b846-cfb1c657bfb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span[2]</value>
      <webElementGuid>addefaff-ca62-4a61-9bbd-832e2686d35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '358.000₫' or . = '358.000₫')]</value>
      <webElementGuid>5762d2f7-937d-44f2-bde4-56bd000349f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
