<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_179.000</name>
   <tag></tag>
   <elementGuidId>22024d2d-90bb-4da2-9f48-f94f441ddc21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.totalprice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart-buy-order-box']/section[3]/div[3]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3f96067d-45d7-44b1-99e1-5b049bdd7347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>totalprice</value>
      <webElementGuid>907e8c5a-18b6-4fad-8877-c135c7d0f424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>179.000₫</value>
      <webElementGuid>92eff056-bc2d-434d-a206-ef0f332e2a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-buy-order-box&quot;)/section[@class=&quot;section-info-total&quot;]/div[@class=&quot;summary-total&quot;]/span[@class=&quot;totalprice&quot;]</value>
      <webElementGuid>4bb1acf9-12c1-4d58-bf00-52e1217ae93a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-buy-order-box']/section[3]/div[3]/span[2]</value>
      <webElementGuid>92969d09-a701-4cb1-bd26-5c372eb51976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền:'])[1]/following::span[1]</value>
      <webElementGuid>7c6fc19c-e201-4333-838d-66f3d0a1c092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Miễn phí'])[1]/following::span[2]</value>
      <webElementGuid>e51d6c46-ea38-4548-8a9e-8e7496832270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ĐẶT HÀNG NGAY'])[1]/preceding::span[1]</value>
      <webElementGuid>a5dde36c-3d91-4403-9046-573b0535f33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin khách mua hàng'])[1]/preceding::span[1]</value>
      <webElementGuid>cecfc082-1bca-4c1b-a8d4-e7fc180e1486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span[2]</value>
      <webElementGuid>ad55ae75-15ec-4535-84d6-71f559777ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '179.000₫' or . = '179.000₫')]</value>
      <webElementGuid>1d207331-e15f-4b6b-a613-5905f1508fa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
