<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_179.000_1</name>
   <tag></tag>
   <elementGuidId>2a6dd259-3d18-4a18-a584-ed3fd7b306ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item-price > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='cartformpage']/div/div/div/div[2]/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d021fd27-01e0-43f8-971c-5461798145c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>179.000₫</value>
      <webElementGuid>41cebdce-5f82-41b4-9555-3899700fefb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartformpage&quot;)/div[@class=&quot;table-cart&quot;]/div[@class=&quot;cart-group single&quot;]/div[@class=&quot;item line-item line-item-container&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;item-meta&quot;]/div[@class=&quot;item-price&quot;]/span[1]</value>
      <webElementGuid>713b0fb7-c552-45de-bb81-ce9e03767f0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cartformpage']/div/div/div/div[2]/div[2]/div/span</value>
      <webElementGuid>7b53438f-b81e-4894-becd-decec09b90ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Màu 1-17] Son Tint Nước Romand Siêu Lì, Lâu Trôi Glasting Water Tint 4g'])[1]/following::span[2]</value>
      <webElementGuid>8a11dbb8-d4cf-41c1-8e58-3a87606364ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xoá'])[1]/following::span[2]</value>
      <webElementGuid>b2935a40-bcdf-4c1c-9ccf-a25503cf991a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thành tiền:'])[1]/preceding::span[2]</value>
      <webElementGuid>c684b8dd-bb57-401f-8776-ffe8b75d7933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sử dụng mã giảm giá'])[1]/preceding::span[4]</value>
      <webElementGuid>75d3fa86-2783-4557-8477-2b1d90f1daad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='179.000₫']/parent::*</value>
      <webElementGuid>7a438ed9-d6fe-4880-bc32-cdcc942a9fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span</value>
      <webElementGuid>f6fc95bd-0afe-411e-8cf9-59d17777a16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '179.000₫' or . = '179.000₫')]</value>
      <webElementGuid>3261582c-a944-4394-a659-4fefdf84e817</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
