<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_02  THM</name>
   <tag></tag>
   <elementGuidId>59458def-6c6f-4a75-9192-19219b59129c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-swatch-item-option1']/div[2]/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>340d512d-77a9-48c3-b297-28613eb56e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>02 ĐỎ THẪM</value>
      <webElementGuid>92cb6ed6-bcfb-4faf-9eb9-c6d9cb32eb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-swatch-item-option1&quot;)/div[@class=&quot;product-swatch-item-element-wrap&quot;]/div[@class=&quot;product-swatch-item-element&quot;]/label[1]/span[1]</value>
      <webElementGuid>1c04b48a-6f7a-4b27-9bde-226e07643d8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-swatch-item-option1']/div[2]/div/label/span</value>
      <webElementGuid>252bcb17-bb43-4cc7-9875-fc7d6c92ef7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiêu đề'])[1]/following::span[1]</value>
      <webElementGuid>1c990043-a897-499b-bb02-e9831fff7ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin Outlet'])[2]/following::span[1]</value>
      <webElementGuid>4b2c303c-85fc-42d2-a7c7-b25cb9b8ccb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[SALE] 04 ĐỎ NÂU'])[2]/preceding::span[2]</value>
      <webElementGuid>ea1e3a03-7ad3-4b12-890b-726fdf6edc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vui lòng chọn biến thể'])[1]/preceding::span[9]</value>
      <webElementGuid>59812e4c-5fbc-4e0c-8335-7552d5044aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>9b522517-627e-442c-8b9e-893b177ebb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '02 ĐỎ THẪM' or . = '02 ĐỎ THẪM')]</value>
      <webElementGuid>d30d91e5-7caf-4a92-8a9e-29c08d5b1a37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
