<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Blind Box - Lucky Emma_q</name>
   <tag></tag>
   <elementGuidId>da85d19c-155b-49c6-8a40-632218be71ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sidenav-search-top-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sidenav-search-top-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5869a62d-de2a-479f-ab61-0424b340ff9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd73e79b-cdc0-4840-9138-eba9bace5932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control js-search-input</value>
      <webElementGuid>a7ce2f59-7343-4bc9-bbce-9da277e5fb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidenav-search-top-input</value>
      <webElementGuid>f6b33830-7c72-425c-aaed-95906e829870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>5f435254-07de-48af-afd2-a77cd6c5a51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm sản phẩm, danh mục hay thương hiệu mong muốn</value>
      <webElementGuid>6d02fce6-36fb-4664-ac12-14384913f7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3eaa51a3-91e8-413b-aec2-53f71d6397cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidenav-search-top-input&quot;)</value>
      <webElementGuid>e1158fdf-c668-4cb1-8bb2-7505d67f268e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sidenav-search-top-input']</value>
      <webElementGuid>40f4fc9d-e33d-4cd6-a5aa-602253186a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidenav']/div/div[3]/div/form/div/input</value>
      <webElementGuid>8abf53b8-42de-4754-8b67-d76df43abaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/div/input</value>
      <webElementGuid>6bcc6234-9bba-4577-b36a-5fe25e9e5474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sidenav-search-top-input' and @name = 'q' and @placeholder = 'Tìm sản phẩm, danh mục hay thương hiệu mong muốn']</value>
      <webElementGuid>a052c015-a955-4273-9f59-904957c64c93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
