<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gi</name>
   <tag></tag>
   <elementGuidId>e86c0e8c-fb25-455a-a8ca-04c1d3437dfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.btn-lg.s_website_form_send</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='helpdesk_ticket_form']/div/div[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e2b98f8c-31a4-4bde-a171-c2d79810bcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3224847d-a986-43a1-9e44-efbe34e0ac0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30a89727-fc69-4c07-99ed-3d3a64868b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg s_website_form_send</value>
      <webElementGuid>591431db-7357-4cb8-bceb-e180ac6c8211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gửi</value>
      <webElementGuid>0128ad5a-754d-4514-8fc3-b26e0cfa282b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;helpdesk_ticket_form&quot;)/div[@class=&quot;s_website_form_rows row s_col_no_bgcolor&quot;]/div[@class=&quot;form-group col-12 s_website_form_submit&quot;]/a[@class=&quot;btn btn-primary btn-lg s_website_form_send&quot;]</value>
      <webElementGuid>f9d645dd-e323-43d8-9b0f-d48a3127a7bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='helpdesk_ticket_form']/div/div[7]/a</value>
      <webElementGuid>6b8b54d8-d243-46ff-b611-b98b60dd5976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gửi')]</value>
      <webElementGuid>eeed61b5-9e8f-4c39-86e6-31f67ddd0678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhóm'])[1]/following::a[1]</value>
      <webElementGuid>17784cc8-a63f-48ba-93d2-b1dd4dd90684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tệp đính kèm'])[1]/following::a[1]</value>
      <webElementGuid>1c932eb5-c215-4737-869d-b7efea38ee27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem vé của tôi'])[1]/preceding::a[1]</value>
      <webElementGuid>ae23453a-1153-430c-a79d-1ab8f393d773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liên kết hữu ích'])[1]/preceding::a[2]</value>
      <webElementGuid>0ef9d456-fa5b-4773-806b-5363041f2a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gửi']/parent::*</value>
      <webElementGuid>7ba6cb15-74f2-4b6a-aa9d-ce110e429e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>3ab93903-559b-4de5-9664-7a20dabfeb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a</value>
      <webElementGuid>545a8f4b-1750-446f-94a8-0dfacf0d9178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Gửi' or . = 'Gửi')]</value>
      <webElementGuid>2f0db0e9-67a9-4b0e-958d-0b68e8ab35ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
