<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__partner_name</name>
   <tag></tag>
   <elementGuidId>b00e1243-609d-4e23-9211-6476db4189bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#helpdesk1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='helpdesk1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d42f7c21-4fdd-4833-a028-15668e6861bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>helpdesk1</value>
      <webElementGuid>54acd005-33ac-4471-a2c8-e1ef93931f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>027ee45b-0f6d-4ec1-8cd3-c594f1a90c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control s_website_form_input</value>
      <webElementGuid>97c0c05c-57e4-4a24-a7ba-e87d06dbc11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>partner_name</value>
      <webElementGuid>2f91ea2c-25a9-4064-86e8-62de589e01bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fe190c59-fd41-487b-972a-e09be5a235d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fill-with</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>bed14bcf-dff5-4749-a676-2d49ffcb71f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;helpdesk1&quot;)</value>
      <webElementGuid>2ba4453a-861c-4810-8ed2-9b2990287ba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='helpdesk1']</value>
      <webElementGuid>78fd0fed-72b4-451d-aa20-45a4de88359b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='helpdesk_ticket_form']/div/div/div/div/input</value>
      <webElementGuid>7ee18d73-6ff5-4123-aa1c-0ede618b058f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>565e933b-7724-4aab-acaa-9c1294c34059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'helpdesk1' and @type = 'text' and @name = 'partner_name']</value>
      <webElementGuid>aecf3160-a40b-4977-b251-90cdad9319bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
