<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__partner_email</name>
   <tag></tag>
   <elementGuidId>c1945f94-fcf6-4b8e-a139-d441b1579531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#helpdesk2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='helpdesk2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a660cf0-6a6f-4c43-b649-fe4aabbb8a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>helpdesk2</value>
      <webElementGuid>e5eaeaf8-15d9-403b-bbe5-e265d90fb699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>cfe35d87-26d3-4333-8569-3db800a3072f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control s_website_form_input</value>
      <webElementGuid>5deebab1-70d4-44c2-8f60-6c0cc92f2eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>partner_email</value>
      <webElementGuid>4bc489ab-fa88-45b3-9be6-68a71a33ee9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>103d3b7b-b4e5-4ad8-89d9-227893b08524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fill-with</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ae0d52a6-ea05-49f6-9549-9ab34d8db1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;helpdesk2&quot;)</value>
      <webElementGuid>5b959461-0d75-4fc7-9c02-01401491410a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='helpdesk2']</value>
      <webElementGuid>3034921d-a974-4092-a4af-add26fddcd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='helpdesk_ticket_form']/div/div[2]/div/div/input</value>
      <webElementGuid>790df799-6fee-4f30-a4f5-3ce01f19178f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>b1ffcbf7-42a7-4951-8033-4ae6c4fc1aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'helpdesk2' and @type = 'email' and @name = 'partner_email']</value>
      <webElementGuid>0d956445-4f1a-4b11-82cd-eff7d384e1f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
