<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__name</name>
   <tag></tag>
   <elementGuidId>c0ce9dd1-e27c-4db6-a01c-78c6039add11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#helpdesk3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='helpdesk3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3f20f11-04ed-488c-ae52-051442e5425c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>helpdesk3</value>
      <webElementGuid>2d9ffbba-1071-48bb-b9c8-c64a485e3721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fbba0b09-fe7a-4489-847f-697a992a1b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control s_website_form_input</value>
      <webElementGuid>587fe931-0b97-4def-95d9-b475eef79a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>f0c823e0-ec75-4e15-906e-5a9882112d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ee4471a5-c9aa-4794-887b-9c27cd60b56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;helpdesk3&quot;)</value>
      <webElementGuid>aacc22b1-d1ba-416b-8e4b-3a20b9d34833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='helpdesk3']</value>
      <webElementGuid>94ee95df-a4f6-4603-b188-d0e903775fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='helpdesk_ticket_form']/div/div[3]/div/div/input</value>
      <webElementGuid>4c383451-d619-41b4-8110-3c5e941c7caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>c0882980-0e84-4284-92f3-ab01c303f6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'helpdesk3' and @type = 'text' and @name = 'name']</value>
      <webElementGuid>66d1053b-cb23-4254-84c8-fee0dbc24655</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
