<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_M t_description</name>
   <tag></tag>
   <elementGuidId>6dbcee4c-a9f2-4856-9971-09225f8c1ec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#helpdesk4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='helpdesk4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>87e54d65-76cc-40d4-95a7-828a4625c4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>helpdesk4</value>
      <webElementGuid>c39ec4d2-08cd-4339-8bfb-c3cadd0d0f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control s_website_form_input</value>
      <webElementGuid>5610a0f5-5e66-4e48-95b7-d0b9ed14c5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>f9725286-8313-4614-8dc7-c0bdee8d2000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;helpdesk4&quot;)</value>
      <webElementGuid>01c56036-4699-4841-9930-490a2815191f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='helpdesk4']</value>
      <webElementGuid>9c53b556-1813-45cd-9ee6-5f37989f8676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='helpdesk_ticket_form']/div/div[4]/div/div/textarea</value>
      <webElementGuid>ed6bb772-a425-482a-a183-4274151e0c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>65551fed-bab3-457b-9372-16124c7c6585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'helpdesk4' and @name = 'description']</value>
      <webElementGuid>1ef20722-b19c-416e-8b57-f18e67f342c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
