<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>01360acc-6e5c-45af-a9bf-2c52942d28b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;support icon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='f-header']/section[2]/div/div/div[4]/div[2]/a[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2abac3dc-bb7f-483c-b387-bde1cb753b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://file.hstatic.net/1000006063/file/photo_2025-02-21_14-39-10.jpg</value>
      <webElementGuid>761c205a-6e73-4f62-aa3a-ab7d2f3fd4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>support icon</value>
      <webElementGuid>fceceb78-e8d2-412e-8b43-74729716843e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>94c3fad7-2a15-4250-b99b-d6de5bf3e128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f-header&quot;)/section[@class=&quot;f-header-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;f-header-top-wrap&quot;]/div[@class=&quot;f-header-top-tools&quot;]/div[@class=&quot;f-header-top-icons&quot;]/a[3]/img[1]</value>
      <webElementGuid>fdef449f-8d31-4e62-be7e-c437cbeba491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='f-header']/section[2]/div/div/div[4]/div[2]/a[3]/img</value>
      <webElementGuid>ff222ee2-d853-4e5a-86f1-0e712bbe8488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='support icon']</value>
      <webElementGuid>ea70c510-d95b-4a9e-b438-96b568f1efec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>655a717c-7240-489e-b2f9-95b902c4b212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://file.hstatic.net/1000006063/file/photo_2025-02-21_14-39-10.jpg' and @alt = 'support icon']</value>
      <webElementGuid>c2edf624-736b-485b-a07b-04469eebeb54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
