<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>137886bb-8553-450e-9668-6abc6a00c9a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.f-header-top-icon-account > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotline: 1900 636 510'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>971aed00-9c27-456f-9ba4-8c0606054f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>6096c63a-a668-46d7-83fe-7e6c7e800598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>4305e073-9132-4930-b7b5-7cdcaadb8a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 22 21</value>
      <webElementGuid>aca1a930-da92-4528-af15-eb292c3b804d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2d90727b-a103-447e-91b2-f6872c58facd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>983e8085-b2f8-4f79-8df5-afceebcefbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f-header&quot;)/section[@class=&quot;f-header-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;f-header-top-wrap&quot;]/div[@class=&quot;f-header-top-tools&quot;]/div[@class=&quot;f-header-top-icons&quot;]/a[@class=&quot;f-header-top-icon-account&quot;]/svg[1]</value>
      <webElementGuid>cfdc5d1b-ab56-459c-b704-91a267b41639</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotline: 1900 636 510'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>1e630ac1-0043-4784-bf67-9ddc85f61702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKINCARE'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>bd4434f8-4f34-4aa6-ace7-9970951bfc27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DANH MỤC SẢN PHẨM'])[1]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>34ffaeee-65d7-46d6-bf8f-e51c5989a96f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang điểm'])[1]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>a5335cd0-f273-4749-9549-a5a86fa9686f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
