<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PHC HI MT KHU_birthday_fake</name>
   <tag></tag>
   <elementGuidId>9d02b077-0115-496c-8e48-2ad4ee9380fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#birthday_fake</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthday_fake']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f28ffd4-89b2-4229-a2b8-ef03bde31d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ae5b66b-610d-485a-97ce-21c992705f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ngày/Tháng/Năm Sinh</value>
      <webElementGuid>200cffbe-11ab-43a4-90fd-387b4da30386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthday_fake</value>
      <webElementGuid>4384fa7a-a0a3-4a4c-90b8-d5f96ba19586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text input-full form-control</value>
      <webElementGuid>f0f0dcfe-c010-421e-a13e-fa36947423ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>02589b68-435e-4753-bf0a-01d5a613f2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthday_fake&quot;)</value>
      <webElementGuid>1d6122d0-1894-45b5-b259-1e6d8e3b2e9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthday_fake']</value>
      <webElementGuid>6972612d-8972-469b-b2cb-d7fe11d47249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create_customer']/div[3]/input[2]</value>
      <webElementGuid>4a25c43b-4ae3-412c-b234-a667ccf0e22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[2]</value>
      <webElementGuid>88a2ab5e-0420-48ec-832c-f9a47a1c1195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Ngày/Tháng/Năm Sinh' and @id = 'birthday_fake']</value>
      <webElementGuid>ae2d5c61-3bea-43fe-9010-10ce99ca9dfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
