<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TO TI KHON_customerpassword</name>
   <tag></tag>
   <elementGuidId>b141a6cd-c23f-43da-a25e-b9f6b3ce9bb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create_customer > div.form-group > input[name=&quot;customer[password]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='customer[password]'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4110c12c-976d-4475-b248-5469e200b8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>00ffa346-de46-4b62-9ab5-4da89bf1f5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật khẩu</value>
      <webElementGuid>2ff8bdeb-250e-48e8-b080-33ec7b588493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d37a3f0d-b2be-449c-adb4-061d668cb3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer[password]</value>
      <webElementGuid>82294932-fb2f-406c-b200-02a06d1b9174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_customer&quot;)/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>6d240de5-dc52-4945-9197-9002fbd265e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='customer[password]'])[2]</value>
      <webElementGuid>4635b0cc-270f-4f8e-82e4-33411985a963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create_customer']/div[5]/input</value>
      <webElementGuid>0be2c480-81ae-405c-8a08-ba1066e06936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>61a09ed8-4783-40ef-bcae-c1c312d26807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Mật khẩu' and @name = 'customer[password]']</value>
      <webElementGuid>c758c5ed-5575-440c-b786-48d6c2fe6d47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
