<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TO TI KHON_birthday_fake</name>
   <tag></tag>
   <elementGuidId>072273f7-51ad-402e-83be-f0e11ad307c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#birthday_fake</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthday_fake']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>057e003b-2101-4ebc-8312-1e6efd702497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d674d58c-ec5a-48c1-9b58-d6bf61b8dd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ngày/Tháng/Năm Sinh</value>
      <webElementGuid>c58a1692-72ff-47ca-ac80-e4942f3f07d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthday_fake</value>
      <webElementGuid>b6fb5690-53d1-4f8e-a626-4c27ed3f081e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text input-full form-control</value>
      <webElementGuid>9eeb14b3-ba4c-4054-beab-3dcadd17084e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>81dc6593-a0c4-4517-bcc4-11c8c9d2219a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthday_fake&quot;)</value>
      <webElementGuid>6198dac2-efae-4e04-8086-8de669dcd13f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthday_fake']</value>
      <webElementGuid>cdeab35c-4507-4f2d-bde9-52669f252141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create_customer']/div[3]/input[2]</value>
      <webElementGuid>519c4ef8-e225-444e-968d-7c5dc54923bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[2]</value>
      <webElementGuid>ab41ed32-df4f-4587-9ba6-6fe1b72bf6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Ngày/Tháng/Năm Sinh' and @id = 'birthday_fake']</value>
      <webElementGuid>3f5a7261-e861-448a-bd92-efa53d1afd9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
