<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_-</name>
   <tag></tag>
   <elementGuidId>a6092b8f-222b-48e9-b1f0-1413d7df4413</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.product-quantity > button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-product']/section/div/div/div[2]/div[10]/div[3]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d3ec4582-0289-435d-a546-17d3db307b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>minus</value>
      <webElementGuid>33d6a173-e3f0-4e67-ba98-4e84e269d7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>53bbe1ee-17fd-44cc-9da2-303c03a11766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-product&quot;)/section[@class=&quot;page-product-info&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;page-product-info-wrap&quot;]/div[@class=&quot;page-product-info-right&quot;]/div[@class=&quot;page-product-select&quot;]/div[@class=&quot;page-product-info-quantity&quot;]/div[@class=&quot;product-quantity&quot;]/button[1]</value>
      <webElementGuid>8462802f-25b5-41e3-bc13-2aaaacd89bd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-product']/section/div/div/div[2]/div[10]/div[3]/div/button</value>
      <webElementGuid>0fcf6479-6095-463e-9043-bd16d6eb35f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số lượng'])[1]/following::button[1]</value>
      <webElementGuid>4ebc546f-ae7a-445c-aec6-e8a73a785669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vui lòng chọn biến thể'])[1]/following::button[1]</value>
      <webElementGuid>f92ac41f-b0e9-462c-bd04-3856a3ffe000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::button[1]</value>
      <webElementGuid>0dbd2adc-f45e-4349-87de-73af9bb6ddc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DƯỠNG SÁNG DA (BẢN MỚI)'])[3]/preceding::button[2]</value>
      <webElementGuid>534cf93d-159d-4dec-8296-73bfcfc3cd3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-']/parent::*</value>
      <webElementGuid>d9c041ab-5a1b-4d76-b0f7-f22ee50f0716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[3]/div/button</value>
      <webElementGuid>a1b56244-91f0-4b6d-82e0-e713ec6df66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '-' or . = '-')]</value>
      <webElementGuid>6ee4f606-8ffd-463a-888a-993f12bee873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
